title: PsyWave Games
show_downloads: false
google_analytics:
description: oh baby, lets make a crazy games and grab dead Presidents!
theme: jekyll-theme-hacker
github:
  another_url: https://github.com/psywave-games
